# Generated by Django 4.0.3 on 2022-03-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
