# Generated by Django 4.0.3 on 2022-03-16 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0004_alter_blogcomment_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='critic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
